services:
    client:
        build:
            context: ./client
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: development
        volumes:
            - ./client:/client
            - ./client/node_modules:/client/node_modules
        develop:
            watch:
                - action: sync
                  path: ./src
                  target: /client/src
                  ignore:
                      - node_modules/
                - action: sync
                  path: ./
                  target: /client
                  ignore:
                      - node_modules/
                      - package.json
    server:
        build:
            context: ./server
        ports:
            - '8000:8000'
            - '5555:5555'
        environment:
            NODE_ENV: development
            DATABASE_URL: postgresql://postgres:abc@postgres:5432/brandon_stock_db
        volumes:
            - ./server:/server
            - ./server/node_modules:/server/node_modules
        command:
            - /bin/sh
            - -c
            - |
                echo "Starting the server..."
                npx prisma generate
                npx prisma db push
                npm run dev
        develop:
            watch:
                - action: sync
                  path: ./src
                  target: /server/src
                  ignore:
                      - node_modules/
                - action: sync
                  path: ./
                  target: /server
                  ignore:
                      - node_modules/
                      - package.json
        depends_on:
            - postgres

    postgres:
        image: postgres:15-alpine
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=brandon_stock_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=abc
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
