services:
    frontend:
        build:
            context: ./client
        ports:
            - '3000:3000'
        environment:
            NEXT_PUBLIC_API_BASE_URL: https://localhost:8000
        volumes:
            - ./client/package.json:/client/package.json
            - ./client/node_modules:/client/node_modules
        command:
            - /bin/sh
            - -c
            - |
                echo "Starting client..."
                npx prisma generate
                npm run dev
        develop:
            watch:
                - action: sync
                  path: ./client/src/
                  target: /client/src
                - action: sync
                  path: ./client/public/
                  target: /client/public
                - action: sync
                  path: ./client/styles/
                  target: /client/styles
                - action: sync
                  path: ./client/package.json
                  target: /client/package.json
    backend:
        build:
            context: ./server
        ports:
            - '8000:8000'
            - '5555:5555'
        environment:
            PORT: 8000
            DATABASE_URL: postgresql://postgres:abc@postgres:5432/brandon_stock_db
        volumes:
            - ./server/package.json:/server/package.json
            - ./server/node_modules:/server/node_modules
        command:
            - /bin/sh
            - -c
            - |
                echo "Starting the server..."
                npx prisma generate
                npx prisma db push
                npm run dev
        develop:
            watch:
                - action: sync
                  path: ./server
                  target: /server
                  ignore:
                      - node_modules/
        depends_on:
            - postgres

    postgres:
        image: postgres:15-alpine
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=brandon_stock_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=abc
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
